config/routes.rb
Rails.application.routes.draw do
  # Home
  root 'pages#home'
  get 'about', to: 'pages#about'

  # Article
  resources :articles

  # Signup
  get 'signup', to: 'users#new'

  # Session
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Users
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  paginates_per 5
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
  paginates_per 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  helper_method :current_user, :logged_in?

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: %i[ index show ]
  before_action :require_same_user, only: %i[ edit update destroy ]

  def index
    @articles = Article.order(:name).page params[:page]
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own articles"
        redirect_to @article
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.order(:name).page params[:page]
  end

  def show
    @articles = @user.articles.order(:name).page params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog, #{@user.username}!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own profile"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  include SessionsHelper
  include UsersHelper
  include ArticlesHelper
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def can_modify_article?(article)
    logged_in? && (current_user.id == article.user.id || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user = nil, options = { size: 200 })
    user ||= @user
    size = options[:size]
    gravatar_id = Digest::SHA256::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block")
  end

  def can_edit_user?(user)
    logged_in? && (current_user.id == user.id || current_user.admin?)
  end

  def admin_user?(user)
    logged_in? && current_user.admin?
  end
end

app/views/articles/_article-card.html.erb
<div class="card text-center shadow-lg mb-5 bg-white rounded">
  <div class="card-header font-italic text-primary">
    <% if article.user %>
      by <%= link_to article.user.username, article.user %>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title text-success"><%= article.title %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
    <div class="row justify-content-center">
      <div class="mx-2">
        <%= link_to 'View', article, class: "btn btn-outline-success" %>
      </div>
      <% if can_modify_article?(article) %>
        <div class="mx-2">
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-primary" %>
        </div>
        <div class="mx-2">
          <%= button_to 'Destroy', article, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
    Edited <%=  time_ago_in_words(article.updated_at) %> ago</small>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <%= render 'shared/errors', obj: article %>

  <div class="container bg-info rounded mt-4 p-4">
    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :title, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_field :title, placeholder: "Title of content", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="field row">
      <div class="col-1">
        <%= form.label :description, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_area :description, placeholder: "Description", rows: "10", class: "form-control input-group input-group-lg" %>
      </div>
    </div>
    <div class="actions text-center">
      <%= form.submit class: "btn btn-outline-light mt-4" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container-sm mb-4">
  <h1 class="text-center mt-4">Edit Article</h1>
  <%= render 'form', article: @article %>
</div>
<div class="container text-center">
  <div class="row">
    <div class="col-1">
      <%= link_to 'Show', @article, class: "btn btn btn-outline-primary" %>     
    </div>
    <div class="col-1">
      <%= link_to 'Back', articles_path, class: "btn btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4">Listing all articles</h1>

<div class="container-sm">
  <%= paginate @articles %>
  <% @articles.each do |article|%>
    <%= render 'article-card', article: article %>
  <% end %>
</div>

<br>

<div class="container-sm">
  <%= link_to 'New Article', new_article_path, class: "btn btn-outline-primary mb-4" %>
</div>

app/views/articles/new.html.erb
<div class="container-sm mb-4">
  <h1 class="text-center mt-4">Create new Article</h1>
  <%= render 'form', article: @article %>
</div>
<div class="container text-center">
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info"  %>
</div>

app/views/articles/show.html.erb
<div class="container-sm mt-4 mb-4">
  <div class="card shadow-lg mb-5 bg-white rounded">
    <div class="card-header text-center">
      <%= link_to gravatar_for(@article.user, size: 80), user_path(@article.user) %>
      <%= @article.user.username %>
    </div>
    <div class="card-body">
      <h5 class="card-title text-success"><%= @article.title %></h5>
      <p class="card-text text-left"><%= simple_format(@article.description) %></p>
        <% if can_modify_article?(@article) %>
          <div class="row justify-content-center">
            <div class="col col col-lg-1">
              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-primary" %>
            </div>
            <div class="col col col-lg-1">
              <%= button_to 'Destroy', @article, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <% end %>
    </div>
    <div class="card-footer text-muted text-center">
      <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
      Edited <%=  time_ago_in_words(@article.updated_at) %> ago</small>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Fábio Oliveira</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="container mt-2">
    <div class="alert alert-success" role="alert">
      <%= notice %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

<% if alert %>
  <div class="container mt-2">
    <div class="alert alert-danger" role="alert">
      <%= alert %>

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand text-uppercase font-weight-bold"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu">
          <% if logged_in? %>
            <%= link_to "Create new Article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
     <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles', articles_path %>
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container mt-4 text-white">
  <div class="jumbotron text-center">
    <h1 class="display-4 font-weight-bold">Hello, world!</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <%= link_to 'Sign up!', signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h2>

    <ul>
      <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render 'shared/errors', obj: @user %>

  <div class="container bg-info rounded mt-4 p-4">
    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :username, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_field :username, placeholder: "Enter a username", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :email, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_field :email, placeholder: "Enter your email address", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :password, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.password_field :password, placeholder: "Choose a password", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="actions text-center">
      <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light mt-4") %>
    </div>
  </div>
<% end %>

app/views/users/_signup-form.html.erb
<%= form_with(model: @user) do |form| %>
  <%= render 'shared/errors', obj: @user %>

  <div class="container bg-info rounded mt-4 p-4">
    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :username, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_field :username, placeholder: "Enter a username", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :email, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.text_field :email, placeholder: "Enter your email address", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="field row mb-4">
      <div class="col-1">
        <%= form.label :password, class: "text-white" %>
      </div>
      <div class="col-11">
        <%= form.password_field :password, placeholder: "Choose a password", class: "form-control input-group input-group-lg" %>
      </div>
    </div>

    <div class="actions text-center">
      <%= form.submit "Sign up", class: "btn btn-outline-light mt-4" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container-sm mb-4">
  <h1 class="text-center mt-4">Edit your profile</h1>
  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<div class="container-sm mt-4 mb-4">
  <h1 class="h1 text-center mb-4">Alpha Bloggers</h1>

  <%= paginate @users %>

  <% @users.each do |user| %>
    <div class="card text-center shadow-lg mb-5 bg-white rounded">
      <div class="card-header text-primary font-italic">
        <%= user.username %>
      </div>
      <div class="card-body">
        <%= gravatar_for(user, size: 80) %>
        <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
        <div class="row justify-content-center">
          <div class="mx-2">
            <%= link_to 'View profile', user, class: "btn btn-outline-success" %>
          </div>
          <% if can_edit_user?(user) %>
            <div class="mx-2">
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-primary" %>
            </div>
          <% end %>
          <% if admin_user?(user) %>
            <div class="mx-2">
              <%= button_to 'Destroy', user_path(user), method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer text-muted">
        <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container-sm mb-4">
  <h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
  <%= render 'form', user: @user %>
</div>
<div class="container text-center">
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info"  %>
</div>

app/views/users/show.html.erb
<div class="container-sm mt-4 mb-4">
  <h1 class="h1 text-center"><%= @user.username %>'s profile</h1>

  <%= gravatar_for(@user) %>

  <% if can_edit_user?(@user) %>
    <div class="text-center mt-4">
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
  <% end %>

  <% if @user.articles.any? %>
    <h2 class="h3 my-5 text-center">Articles by <%= @user.username %>:</h2> 
    <%= paginate @articles %>
    <% @articles.each do |article| %>
      <%= render 'articles/article-card', article: article %>
    <% end %>
  <% end %>
</div>